{% set name = "seml" %}
{% set version = "0.3.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/seml-{{ version }}.tar.gz
  sha256: 1aaca4a826674ee3a52fa3df22d700d8770a215569079b320915502b6254a488

build:
  number: 0
  skip: true  # [win]
  entry_points:
    - seml = seml.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - debugpy >=1.2.1
    - jsonpickle >=1.2,<2.0
    - munch >=2.0.4
    - numpy >=1.15
    - pandas
    - pymongo >=3.7,<4.0
    - python
    - pyyaml >=5.1
    - sacred >=0.8.1
    - tqdm >=4.36

test:
  imports:
    - seml
  commands:
    - pip check
    - seml --help
  requires:
    - pip

about:
  home: http://github.com/TUM-DAML/seml
  summary: Slurm Experiment Management Library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - siboehm
