{% set name = "seml" %}
{% set version = "0.4.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/seml-{{ version }}.tar.gz
  sha256: 874e46be6c1f6b7bd24f51b82f39c467b6e078a4429f4e0ba8fe24e2cd7a3138

build:
  number: 0
  skip: true  # [win]
  entry_points:
    - seml = seml.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.15
    - pymongo >=3.11
    - pandas
    - sacred >=0.8.4
    - pyyaml >=5.1
    - jsonpickle >=2.2
    - munch >=2.0.4
    - tqdm >=4.36
    - debugpy >=1.2.1
    - requests >=2.28.1
    - typer >=0.9
    - rich >=13.0
    - omegaconf >=2.3.0
    - typing_extensions
    - python

test:
  imports:
    - seml
  commands:
    - pip check
    - seml --help
  requires:
    - pip

about:
  home: http://github.com/TUM-DAML/seml
  summary: Slurm Experiment Management Library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - n-gao
    - siboehm
